- name: install nginx
  hosts: frontend
  become: yes
  serial: 3
  tasks:
  - name: hello world
    debug:
      msg: "Hello World"
  - name: install nginx
    package:
      name: nginx
      state: present